USE [master]
GO
/****** Object:  Database [BookStoreAuthDB]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE DATABASE [BookStoreAuthDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookStoreAuthDB', FILENAME = N'C:\Users\user\BookStoreAuthDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookStoreAuthDB_log', FILENAME = N'C:\Users\user\BookStoreAuthDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BookStoreAuthDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookStoreAuthDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookStoreAuthDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BookStoreAuthDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookStoreAuthDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookStoreAuthDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BookStoreAuthDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookStoreAuthDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookStoreAuthDB] SET  MULTI_USER 
GO
ALTER DATABASE [BookStoreAuthDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookStoreAuthDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookStoreAuthDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookStoreAuthDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookStoreAuthDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookStoreAuthDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BookStoreAuthDB] SET QUERY_STORE = OFF
GO
USE [BookStoreAuthDB]
GO
/****** Object:  Table [dbo].[BLACKLISTS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BLACKLISTS](
	[BlacklistID] [int] IDENTITY(1,1) NOT NULL,
	[MemberID] [int] NOT NULL,
	[Reason] [nvarchar](200) NULL,
	[SourceType] [tinyint] NOT NULL,
	[StartAt] [datetime2](7) NOT NULL,
	[EndAt] [datetime2](7) NULL,
	[LiftedByUserID] [int] NULL,
	[LiftedAt] [datetime2](7) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BlacklistID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[vw_BlacklistActive]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/* === VIEW: must be first in batch === */
CREATE VIEW [dbo].[vw_BlacklistActive] AS
SELECT *
FROM dbo.BLACKLISTS
WHERE StartAt <= SYSUTCDATETIME()
  AND (EndAt IS NULL OR EndAt > SYSUTCDATETIME())
  AND LiftedAt IS NULL;
GO
/****** Object:  Table [dbo].[FEATURES]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEATURES](
	[FeatureID] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](100) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Group] [nvarchar](100) NULL,
	[IsPageLevel] [bit] NOT NULL,
	[SortOrder] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FeatureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER_CREDENTIALS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER_CREDENTIALS](
	[MemberID] [int] NOT NULL,
	[Account] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](200) NOT NULL,
	[PasswordSalt] [nvarchar](200) NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Account] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER_EXTERNAL_LOGINS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER_EXTERNAL_LOGINS](
	[BindingID] [bigint] IDENTITY(1,1) NOT NULL,
	[MemberID] [int] NOT NULL,
	[Provider] [varchar](50) NOT NULL,
	[ProviderKey] [nvarchar](200) NOT NULL,
	[DisplayName] [nvarchar](100) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BindingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_MEL] UNIQUE NONCLUSTERED 
(
	[Provider] ASC,
	[ProviderKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBERS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBERS](
	[MemberID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](254) NULL,
	[Phone] [varchar](20) NULL,
	[Role] [tinyint] NOT NULL,
	[Status] [tinyint] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[TotalBooks] [int] NOT NULL,
	[TotalBorrows] [int] NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION_FEATURES]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION_FEATURES](
	[PermissionID] [int] NOT NULL,
	[FeatureID] [int] NOT NULL,
 CONSTRAINT [PK_PERMISSION_FEATURES] PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC,
	[FeatureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION_SET_ITEMS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION_SET_ITEMS](
	[PermissionSetID] [int] NOT NULL,
	[PermissionID] [int] NOT NULL,
 CONSTRAINT [PK_PSI] PRIMARY KEY CLUSTERED 
(
	[PermissionSetID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSION_SETS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION_SETS](
	[PermissionSetID] [int] IDENTITY(1,1) NOT NULL,
	[SetCode] [varchar](50) NOT NULL,
	[SetName] [varchar](100) NOT NULL,
	[Description] [varchar](200) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionSetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SetCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSIONS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSIONS](
	[PermissionID] [int] IDENTITY(1,1) NOT NULL,
	[PermKey] [varchar](100) NOT NULL,
	[PermName] [varchar](100) NOT NULL,
	[PermGroup] [varchar](100) NULL,
	[Note] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PermKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE_PERMISSIONS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE_PERMISSIONS](
	[RoleID] [int] NOT NULL,
	[PermissionID] [int] NOT NULL,
 CONSTRAINT [PK_ROLE_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleCode] [varchar](50) NOT NULL,
	[RoleName] [varchar](100) NOT NULL,
	[RoleScope] [tinyint] NOT NULL,
	[Description] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RoleCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER_USERS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER_USERS](
	[SupplierID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_SUPPLIER_USERS] PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIERS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIERS](
	[SupplierID] [int] IDENTITY(1,1) NOT NULL,
	[SupplierCode] [varchar](50) NOT NULL,
	[SupplierName] [varchar](100) NOT NULL,
	[ContactEmail] [nvarchar](254) NULL,
	[ContactPhone] [varchar](20) NULL,
	[Status] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SupplierCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_LOGIN_HISTORY]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_LOGIN_HISTORY](
	[LoginID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[OccurredAt] [datetime2](7) NOT NULL,
	[IsSuccess] [bit] NOT NULL,
	[IpAddress] [varchar](45) NULL,
	[UserAgent] [varchar](200) NULL,
	[FailReason] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[LoginID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_PERMISSION_SETS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_PERMISSION_SETS](
	[UserID] [int] NOT NULL,
	[PermissionSetID] [int] NOT NULL,
 CONSTRAINT [PK_UPS] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[PermissionSetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_PERMISSIONS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_PERMISSIONS](
	[UserID] [int] NOT NULL,
	[PermissionID] [int] NOT NULL,
	[Mode] [int] NOT NULL,
 CONSTRAINT [PK_USER_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_ROLES]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_ROLES](
	[UserID] [int] NOT NULL,
	[RoleID] [int] NOT NULL,
 CONSTRAINT [PK_USER_ROLES] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 2025/9/17 下午 02:36:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserType] [tinyint] NOT NULL,
	[Email] [nvarchar](254) NOT NULL,
	[Phone] [varchar](20) NULL,
	[Status] [tinyint] NOT NULL,
	[LastLoginAt] [datetime2](7) NULL,
	[FailedAccessCount] [int] NOT NULL,
	[LockoutEndAt] [datetime2](7) NULL,
	[PasswordHash] [nvarchar](200) NULL,
	[MustChangePassword] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_BL_Member_Period]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_BL_Member_Period] ON [dbo].[BLACKLISTS]
(
	[MemberID] ASC,
	[StartAt] ASC,
	[EndAt] ASC
)
INCLUDE([LiftedAt],[SourceType]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_MEL_Member]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_MEL_Member] ON [dbo].[MEMBER_EXTERNAL_LOGINS]
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_MEMBERS_CreatedAt]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_MEMBERS_CreatedAt] ON [dbo].[MEMBERS]
(
	[CreatedAt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_MEMBERS_Status]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_MEMBERS_Status] ON [dbo].[MEMBERS]
(
	[Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_MEMBERS_Username]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_MEMBERS_Username] ON [dbo].[MEMBERS]
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_MEMBERS_Email_NotNull]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_MEMBERS_Email_NotNull] ON [dbo].[MEMBERS]
(
	[Email] ASC
)
WHERE ([Email] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_MEMBERS_Phone_NotNull]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_MEMBERS_Phone_NotNull] ON [dbo].[MEMBERS]
(
	[Phone] ASC
)
WHERE ([Phone] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ULH_User_Time]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE NONCLUSTERED INDEX [IX_ULH_User_Time] ON [dbo].[USER_LOGIN_HISTORY]
(
	[UserID] ASC,
	[OccurredAt] DESC
)
INCLUDE([IsSuccess],[IpAddress]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_USERS_Email]    Script Date: 2025/9/17 下午 02:36:35 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_USERS_Email] ON [dbo].[USERS]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BLACKLISTS] ADD  CONSTRAINT [DF_BL_Source]  DEFAULT ((2)) FOR [SourceType]
GO
ALTER TABLE [dbo].[BLACKLISTS] ADD  CONSTRAINT [DF_BL_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[FEATURES] ADD  DEFAULT ((0)) FOR [IsPageLevel]
GO
ALTER TABLE [dbo].[FEATURES] ADD  DEFAULT ((0)) FOR [SortOrder]
GO
ALTER TABLE [dbo].[MEMBER_CREDENTIALS] ADD  CONSTRAINT [DF_MC_UpdatedAt]  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[MEMBER_EXTERNAL_LOGINS] ADD  CONSTRAINT [DF_MEL_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_Role]  DEFAULT ((0)) FOR [Role]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_Status]  DEFAULT ((1)) FOR [Status]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_UpdatedAt]  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_TotalBooks]  DEFAULT ((0)) FOR [TotalBooks]
GO
ALTER TABLE [dbo].[MEMBERS] ADD  CONSTRAINT [DF_MEMBERS_TotalBorrows]  DEFAULT ((0)) FOR [TotalBorrows]
GO
ALTER TABLE [dbo].[PERMISSION_SETS] ADD  CONSTRAINT [DF_PS_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[PERMISSION_SETS] ADD  CONSTRAINT [DF_PS_UpdatedAt]  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[SUPPLIERS] ADD  CONSTRAINT [DF_SUPPLIERS_Status]  DEFAULT ((1)) FOR [Status]
GO
ALTER TABLE [dbo].[USER_PERMISSIONS] ADD  CONSTRAINT [DF_USER_PERMISSIONS_Mode]  DEFAULT ((1)) FOR [Mode]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_Status]  DEFAULT ((1)) FOR [Status]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_Failed]  DEFAULT ((0)) FOR [FailedAccessCount]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_MustChange]  DEFAULT ((0)) FOR [MustChangePassword]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_UpdatedAt]  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[BLACKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_BL_LiftedBy] FOREIGN KEY([LiftedByUserID])
REFERENCES [dbo].[USERS] ([UserID])
GO
ALTER TABLE [dbo].[BLACKLISTS] CHECK CONSTRAINT [FK_BL_LiftedBy]
GO
ALTER TABLE [dbo].[BLACKLISTS]  WITH CHECK ADD  CONSTRAINT [FK_BL_MEMBERS] FOREIGN KEY([MemberID])
REFERENCES [dbo].[MEMBERS] ([MemberID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BLACKLISTS] CHECK CONSTRAINT [FK_BL_MEMBERS]
GO
ALTER TABLE [dbo].[MEMBER_CREDENTIALS]  WITH CHECK ADD  CONSTRAINT [FK_MC_MEMBERS] FOREIGN KEY([MemberID])
REFERENCES [dbo].[MEMBERS] ([MemberID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MEMBER_CREDENTIALS] CHECK CONSTRAINT [FK_MC_MEMBERS]
GO
ALTER TABLE [dbo].[MEMBER_EXTERNAL_LOGINS]  WITH CHECK ADD  CONSTRAINT [FK_MEL_MEMBERS] FOREIGN KEY([MemberID])
REFERENCES [dbo].[MEMBERS] ([MemberID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MEMBER_EXTERNAL_LOGINS] CHECK CONSTRAINT [FK_MEL_MEMBERS]
GO
ALTER TABLE [dbo].[PERMISSION_FEATURES]  WITH CHECK ADD  CONSTRAINT [FK_PF_F] FOREIGN KEY([FeatureID])
REFERENCES [dbo].[FEATURES] ([FeatureID])
GO
ALTER TABLE [dbo].[PERMISSION_FEATURES] CHECK CONSTRAINT [FK_PF_F]
GO
ALTER TABLE [dbo].[PERMISSION_FEATURES]  WITH CHECK ADD  CONSTRAINT [FK_PF_P] FOREIGN KEY([PermissionID])
REFERENCES [dbo].[PERMISSIONS] ([PermissionID])
GO
ALTER TABLE [dbo].[PERMISSION_FEATURES] CHECK CONSTRAINT [FK_PF_P]
GO
ALTER TABLE [dbo].[PERMISSION_SET_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_PSI_P] FOREIGN KEY([PermissionID])
REFERENCES [dbo].[PERMISSIONS] ([PermissionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PERMISSION_SET_ITEMS] CHECK CONSTRAINT [FK_PSI_P]
GO
ALTER TABLE [dbo].[PERMISSION_SET_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_PSI_PS] FOREIGN KEY([PermissionSetID])
REFERENCES [dbo].[PERMISSION_SETS] ([PermissionSetID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PERMISSION_SET_ITEMS] CHECK CONSTRAINT [FK_PSI_PS]
GO
ALTER TABLE [dbo].[ROLE_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_RP_PERM] FOREIGN KEY([PermissionID])
REFERENCES [dbo].[PERMISSIONS] ([PermissionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ROLE_PERMISSIONS] CHECK CONSTRAINT [FK_RP_PERM]
GO
ALTER TABLE [dbo].[ROLE_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_RP_ROLES] FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLES] ([RoleID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ROLE_PERMISSIONS] CHECK CONSTRAINT [FK_RP_ROLES]
GO
ALTER TABLE [dbo].[SUPPLIER_USERS]  WITH CHECK ADD  CONSTRAINT [FK_SU_SUP] FOREIGN KEY([SupplierID])
REFERENCES [dbo].[SUPPLIERS] ([SupplierID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SUPPLIER_USERS] CHECK CONSTRAINT [FK_SU_SUP]
GO
ALTER TABLE [dbo].[SUPPLIER_USERS]  WITH CHECK ADD  CONSTRAINT [FK_SU_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[USERS] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SUPPLIER_USERS] CHECK CONSTRAINT [FK_SU_USER]
GO
ALTER TABLE [dbo].[USER_LOGIN_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_ULH_USERS] FOREIGN KEY([UserID])
REFERENCES [dbo].[USERS] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_LOGIN_HISTORY] CHECK CONSTRAINT [FK_ULH_USERS]
GO
ALTER TABLE [dbo].[USER_PERMISSION_SETS]  WITH CHECK ADD  CONSTRAINT [FK_UPS_PS] FOREIGN KEY([PermissionSetID])
REFERENCES [dbo].[PERMISSION_SETS] ([PermissionSetID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_PERMISSION_SETS] CHECK CONSTRAINT [FK_UPS_PS]
GO
ALTER TABLE [dbo].[USER_PERMISSION_SETS]  WITH CHECK ADD  CONSTRAINT [FK_UPS_U] FOREIGN KEY([UserID])
REFERENCES [dbo].[USERS] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_PERMISSION_SETS] CHECK CONSTRAINT [FK_UPS_U]
GO
ALTER TABLE [dbo].[USER_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_UP_PERM] FOREIGN KEY([PermissionID])
REFERENCES [dbo].[PERMISSIONS] ([PermissionID])
GO
ALTER TABLE [dbo].[USER_PERMISSIONS] CHECK CONSTRAINT [FK_UP_PERM]
GO
ALTER TABLE [dbo].[USER_PERMISSIONS]  WITH CHECK ADD  CONSTRAINT [FK_UP_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[USERS] ([UserID])
GO
ALTER TABLE [dbo].[USER_PERMISSIONS] CHECK CONSTRAINT [FK_UP_USER]
GO
ALTER TABLE [dbo].[USER_ROLES]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLES_ROLES] FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLES] ([RoleID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_ROLES]
GO
ALTER TABLE [dbo].[USER_ROLES]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLES_USERS] FOREIGN KEY([UserID])
REFERENCES [dbo].[USERS] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_ROLES] CHECK CONSTRAINT [FK_USER_ROLES_USERS]
GO
USE [master]
GO
ALTER DATABASE [BookStoreAuthDB] SET  READ_WRITE 
GO
