// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class BorrowRecord
{
    [Key]
    public int RecordID { get; set; }

    public int ListingID { get; set; }

    public int MemberID { get; set; }

    public int? ReservationID { get; set; }

    public DateTime BorrowDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public DateTime DueDate { get; set; }

    public byte StatusCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte? ReturnCondition { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<PenaltyTransaction> PenaltyTransactions { get; set; } = new List<PenaltyTransaction>();

    public virtual Reservation Reservation { get; set; }
}