// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class Listing
{
    [Key]
    public int ListingID { get; set; }

    public int CategoryID { get; set; }

    public int PublisherID { get; set; }

    public string Title { get; set; }

    public string ISBN { get; set; }

    public string Condition { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte Status { get; set; }

    public bool? IsAvailable { get; set; }

    public virtual ICollection<BorrowRecord> BorrowRecords { get; set; } = new List<BorrowRecord>();

    public virtual Category Category { get; set; }

    public virtual ICollection<ListingAuthor> ListingAuthors { get; set; } = new List<ListingAuthor>();

    public virtual ICollection<ListingImage> ListingImages { get; set; } = new List<ListingImage>();

    public virtual Publisher Publisher { get; set; }

    public virtual Reservation Reservation { get; set; }
}