// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class ListingAuthor
{
    [Key]
    public int ListingAuthorID { get; set; }

    public int ListingID { get; set; }

    public string AuthorName { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Listing Listing { get; set; }
}