// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class ListingImage
{
    [Key]
    public int ImageID { get; set; }

    public int ListingID { get; set; }

    public string ImageUrl { get; set; }

    public string Caption { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Listing Listing { get; set; }
}