// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class PenaltyRule
{
    [Key]
    public int RuleID { get; set; }
    [Required(ErrorMessage = "ReasonCode 為必填")]
    public string ReasonCode { get; set; }
    [Required(ErrorMessage = "ChargeType 為必填")]
    public string ChargeType { get; set; }
    [Required(ErrorMessage = "UnitAmount 為必填")]
    [Range(1, int.MaxValue, ErrorMessage = "UnitAmount 必須大於 0")]
    public int UnitAmount { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<PenaltyTransaction> PenaltyTransactions { get; set; } = new List<PenaltyTransaction>();
}