// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookLoop.Models;

public partial class PenaltyTransaction
{
    [Key]
    public int PenaltyID { get; set; }

    public int RecordID { get; set; }

    public int MemberID { get; set; }

    public int RuleID { get; set; }

    public DateTime CreatedAt { get; set; }

    public int Quantity { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Member Member { get; set; }

    public virtual BorrowRecord Record { get; set; }

    public virtual PenaltyRule Rule { get; set; }
}