// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookLoop.Models;

public partial class Reservation
{
    public int ReservationID { get; set; }

    public int ListingID { get; set; }

    public int MemberID { get; set; }

    public DateTime ReservationAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? ReadyAt { get; set; }

    public byte Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte ReservationType { get; set; }

    public DateTime? RequestedPickupDate { get; set; }

    public virtual ICollection<BorrowRecord> BorrowRecords { get; set; } = new List<BorrowRecord>();

    public virtual Listing Listing { get; set; }

    public virtual Member Member { get; set; }
}